### ISSUE TITLE
sio_sine example could use phase wrap around

### ISSUE THREAD

**Issue by peeeeter** [andrewrk/libsoundio#110]
Just a quick hint, this example suffers from pretty bad distortion if you let it run long enough (a couple of minutes). The cause by lack of sub-PI precision as the current time gets really large.  The fix for this is to track phase in radians, instead of seconds, and then always adjust / wrap the value by factors of 2*PI to be close to 0.  

Kinda minor, but if you're testing out the framework for the first time, and don't notice this, you might think there is something going one with data corruption, but no, it's just the floating point precision of the generator.

**Comment by iskunk** [comment]
Hi @peeeeter,

It takes some time for the distortion to become really noticeable, but if one changes the starting value of `seconds_offset` from `0.0` to something like `50000.0`, then you're definitely in non-sine territory.

The fix for this is straightforward. No need to switch from seconds to radians---since the frequency (440 Hz) is always in terms of cycles per second, you only need the fractional part of the second.

Could you give [this one-line fix](https://github.com/andrewrk/libsoundio/files/517948/libsoundio-issue110-fix.patch.txt) a try?

**Comment by andrewrk** [comment]
Thanks for the suggested fix. Fixed on the website as well.
