### ISSUE TITLE
Support reversing pointer in SoundIoRingBuffer

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#117]
In implementing a new backend, I found that it is useful to be able to roll back the ring buffer's read pointer, specifically to "recover" samples that may already have been copied to the hardware buffer and can no longer be obtained by other means.

Here is a sample implementation:

```
void soundio_ring_buffer_reverse_read_ptr(struct SoundIoRingBuffer *rb, int count) {
    long read_offset = SOUNDIO_ATOMIC_LOAD(rb->read_offset);
    if (count > read_offset)
        count = (int)read_offset;
    SOUNDIO_ATOMIC_FETCH_ADD(rb->read_offset, -count);
    assert(soundio_ring_buffer_fill_count(rb) >= 0);
}
```

**Comment by Yepoleb** [comment]
> to "recover" samples that may already have been copied to the hardware buffer and can no longer be obtained by other means.

What's the use case for this? Wouldn't `soundio_ring_buffer_advance_write_ptr(-count)` do the same thing without the safety check?

**Comment by iskunk** [comment]
The main use case so far is gap-less pausing with OSS4's write() interface, which I've been working on.

When you do a pause, the hardware buffer is cleared, and you lose whatever samples were there. If you then continue playback from the point where you last wrote samples into the buffer, then you'll have a short segment of audio unaccounted for. If you try to "splice" out the pause, you end up with a gap.

With a reversible ring buffer, as long as new frames haven't overwritten the oldest ones, you can "back up" a bit and recover the frames that had previously been written to the hardware buffer, and feed those to the device once again.

Yes, you can "advance" the pointer by a negative amount, but it's safer to have a separate routine that performs more careful checking. This _is_ a special-case situation, after all.

**Comment by andrewrk** [comment]
I don't think this is a problem we should solve in the Ring Buffer API. I think this problem is deeper and reversing a ring buffer is asking for trouble.

Let's talk about how various things should work, ideally. For these use cases, let's pretend that we're dealing with a large hardware buffer, 1 second long.

Use case 1: implementing seek to a different song in a music player.

In this use case let's assume that we're in the middle of playing one song and we want to immediately seek to a different one, with no gap in the audio. So we have 1 second of song A in the hardware buffer. What we actually want to do, I think, is:

 * Pause the hardware.
 * Clear the hardware buffer.
 * Fill it up to the first 1 second of song B.
 * Resume the hardware.

In this use case if pausing the hardware also clears it, it still perfectly fits our use case.

Use case 2: implementing pause/resume in a music player.

Here let's say we're in the middle of playing a song, and the user presses pause, waits 10 seconds, and then presses resume. When the user presses pause, what we want to happen is pause the hardware, preserving the 1 second of buffered song. When the user resumes, what we want to happen is to resume the hardware. It will pick up right where it left off.

In this case, if pausing the hardware also clears it, our use case is broken.

For libsoundio, it is already true that not all backends support pausing, for example JACK. If OSS4 does not implement pause and resume in a way that is consistent or useful with the other backends, it's acceptable to have it return `SoundIoBackendIncompatible`.

In my experience, pause and resume in general have not been reliable to abstract over. If I were doing it again I might omit pause/resume from the API altogether and suggest that users disconnect/reconnect from the backend to accomplish this.

The downside to this is that these two use cases I outlined above become difficult to achieve correctly. How would you do these use cases in JACK, where there is no pause/resume? You would have to treat it as if any samples written to JACK were lost and would be played no matter what. So for the pause/resume music player use case, whatever your out stream latency is, that's how long it takes to pause. For the seek use case, same thing, your out stream latency determines how long it takes to seek.

What is the conclusion of all this? I'm not sure. I'm just trying to clarify my thoughts. But I'm fairly certain that reversing the pointer in a ring buffer is not a step in the right direction.

Currently ring buffers are only used in the dummy implementation, to mimic a real hardware backend. Using a ring buffer in another implementation is a code smell, since libsoundio is trying to be minimal overhead.

Let's continue the talk about how to make the API work well and how to make robust backend implementations, but I'm going to close the idea of adding this API to ring buffer.
