### ISSUE TITLE
sio_record creates overflows

### ISSUE THREAD

**Issue by 7890** [andrewrk/libsoundio#12]
testing 
```
./sio_record --backend jack a.wav
```
with JACK (dummy backend) running at different period sizes creates storms of overflows (grouped from a few to many, depending on period size), in intervals.
i.e. 10 overflows, silent, 10 overflows, etc.
JACK tells
```
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = SoundIoInStream was not finished, state = Triggered
```
I couldn't find parts in the code that would testwise create these xruns so i suppose they aren't intentional.

a related note, running 
```
./sio_sine --backend jack
```
works without any xruns at very low period sizes.

**Comment by andrewrk** [comment]
I am able to reproduce this behavior if I make the period size small, such as 5ms or less. I think the problem is that the example code calls `fwrite` in `read_callback`, and for low latencies it is best to not make syscalls (such as `write`) in audio callbacks.

To solve this problem we could make the example put data in a ring buffer in the `read_callback` and then call fwrite in another thread.

The reason I didn't already do this is that now the example code has to create a thread on multiple platforms (linux, osx, windows) and this requires os-specific code per platform.

Perhaps I could make the sio_record a test instead of an example, and then it can use the internal OS-specific interfaces for creating threads. Hence, it could still be used as example code in the documentation, but it would not get installed to `/usr/bin/sio_record` or serve as a standalone example that works with no other dependencies than libsoundio.

**Comment by 7890** [comment]
Yes, something along those lines.
I've tested from period size of 8 (sine works flawlessly) up to 256 and then stopped, only the count of overflows did change (but still grouped in "swarms") with sio_record. A period size of 256 or lower (i.e. 64) is not uncommon in a JACK setup.
Considering the focus of the library, this example for the "in" part should work as good as it can be done in an optimal way. I see the problem with thread libraries that are different on platforms and that this part is effectively not at the core of libsoundio. OTOH this is a very common usecase of the lib, so the example should show it in the best way. You can think of people basing their code on that example if works very good (that is writing data to disk, no strings attached). For testing limits, it could have an option to increment the channel count to see where anything starts to break, my 2 cent

**Comment by andrewrk** [comment]
@7890 try out the above change with libsoundio compiled in release mode (this turns on -O2) and see what you think.

**Comment by 7890** [comment]
@andrewrk indeed, that's much better.
The last remaining bit would be to handle ctrl+c nicely to shutdown everyting (again, not at the core of libsoundio but important for the example). That's so far the only case i can see xruns (looks good while recording at low FPP)!

**Comment by andrewrk** [comment]
I'm going to settle for a code comment explaining this. I don't think it's libsoundio's job to demonstrate signal handling.

**Comment by 7890** [comment]
the sio_sine example has a 'q' for quit option, while sio_record hasn't and the only way to stop is ctrl+c which again produces xruns at high probability. I think it should offer at least one way to close down properly for completeness.

**Comment by andrewrk** [comment]
I can't think of a way to do this that is cross platform and does not add another dependency besides libsoundio. Can you?

**Comment by 7890** [comment]
Maybe that's true. That means this example just records endlessly and there is no official way to stop it cleanly across all platforms.
A detail really. The lib is very promising.
