### ISSUE TITLE
Ambiguous name: soundio_version_patch()

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#133]
`soundio_version_patch()` is a somewhat confusing name, partly in that it may suggest a "patch" in the sense of a [synthesizer patch](https://en.wikipedia.org/wiki/Synthesizer#Patch) (as we're operating in the audio/sound domain here), and partly in "patch" being read as a verb. ("Patchlevel" would be a better word, but then that is a bit long.)

A good name I often see for this third term of a version triplet is "micro".

**Comment by minecrawler** [comment]
Personally, I do not find the name to be confusing. It cannot be a synthesizer patch, as it also has `version` in its name. Additionally, I think that `patch` is the better word, as it is more semantic. You commit a patch and then increment the third number in the version string, so it is the "patch number". That naming is perfectly in sync with [SemVer](http://semver.org/).

**Comment by iskunk** [comment]
> It cannot be a synthesizer patch, as it also has version in its name.

From Wikipedia: "A synthesizer **patch** (some manufacturers chose the term **program**) is a sound setting." Programs can be versioned, yes?

Sure, libsoundio doesn't deal with synth patches, but you already know the library through and through. I'm looking at this the way someone who is unfamiliar with the project would.

> Additionally, I think that patch is the better word, as it is more semantic. You commit a patch and then increment the third number in the version string, so it is the "patch number".

Multiple patches can go into a single X.Y.* increment, and patches can bump the minor and major versions, too. It's not a one-to-one mapping.

Wasn't familiar with SemVer, interesting. But what that proposal talks about is the semantics associated with version triplets, not necessarily specific use of the term "patch." There is broad agreement on the use of "major" and "minor," but not as much on the third term.

**Comment by tresf** [comment]
Probably not worth any more discussion, but I did a bit of research on this and `PATCH` definitely seems to change between projects.

FYI, LMMS recently [switched away from `PATCH`](https://github.com/LMMS/lmms/commit/5eb0ae2d7576a12e7a2cd16e4bae7baeeee41c83) after some discussion.

 * Pidgin:  `PURPLE_MICRO_VERSION`
 * LMMS: `VERSION_RELEASE`
 * Gimp: `micro_version`
 * SDL: `patch`
 * TNT: `TNT_SUBMINOR_VERSION`
 * Blender: `foo_micro`

**Comment by minecrawler** [comment]
>  not necessarily specific use of the term "patch."

That's not true. They define the name of the third number in a version to be called "PATCH":

> Given a version number MAJOR.MINOR.PATCH

(first sentence on the website)

----


> Probably not worth any more discussion

I wouldn't say that. The move away from the patch keyword is quite interesting. I don't really keep track of the mentioned projects, as I work without a framework and only use libraries, like libsoundio. What I know is that, especially in web development, SemVer is established. Since I do a lot of web development in addition to working on my game project, I might be quite focused on the SemVer standard. That's why I am a little bewildered by the "micro" keyword. But if it helps and a lot of other libraries hop onto the "micro"-train, then it might help keep things clear.

In the end, though, it is Andrew's decision....
