### ISSUE TITLE
Should this be officially archived/abandoned?

### ISSUE THREAD

**Issue by 0joshuaolson1** [andrewrk/libsoundio#181]
Consider the number of unaddressed issues and the age of the `v2` branch. Has everyone involved moved on? The `v2` branch is the only one that supports my output hardware, but I wonder if JUCE's or QT's licenses would allow someone to look at how they handle more complex devices and continue making basic progress on something like this?

**Comment by andrewrk** [comment]
no

**Comment by 0joshuaolson1** [comment]
Yay!

What about the second question?

**Comment by andrewrk** [comment]
I don't know the answer to that question. 

I understand that I've not been on top of maintenance work on this library, and I won't be for a while longer yet. But you can bet your bottom dollar this is not abandoned. Here's my plan:
 * zig 0.2.0 release
 * rewrite groove basin music player in zig
   - this version will depend on libsoundio instead of SDL
   - libsoundio will get rewritten in zig, with a C API exposed
      - this actually makes it no longer depend on libc on windows, better for static executables.
 * continue work on my DAW using libsoundio and zig

it's a bit of a roundabout journey, and the folks who want a single .c file to drop in their MSVC projects won't be happy. 

but that's how it's gonna happen. those who want to be on board, great. those who don't,  :sunglasses:  bye!
