### ISSUE TITLE
Using libsoundio in a VOIP like application

### ISSUE THREAD

**Issue by avitex** [andrewrk/libsoundio#43]
I have been playing around with the library and samples, and have had much success, but I now have an use case of this library and would like to understand how best to implement it with libsoundio.
As the title suggests, my end goal is sending encoded audio over the net, in my case using the opus project and UDP. My application also has a requirement of having a practical low latency for environments say, like gaming.

- Where would a encoder, best be implemented. For example, the read callback, or in the main loop?
- Would it be appropriate to send the encoded opus audio (UDP) from the read callback or within the main loop?
- How best should the data be read from the read callback to feed straight into the encoder?
For example, the examples provided for libsoundio iterates over the frames and samples, and copies them into a ring buffer. Would there be a better method that uses the data straight off the bat, rather than encoding it?

Thanks in advance.

**Comment by andrewrk** [comment]
In general, you want the code in the write_callback and read_callback to be real time safe. This means you want to avoid operations that might take an indeterminant amount of time, such as acquiring a lock on a mutex, going to sleep, accessing the file system, or using the network. This is true especially if you want to achieve low latency.

You're encoding in real-time, which means it should be safe to put the encoding in the read_callback. As long as the encoding process can guarantee that encoding X amount of frames will take at most Y amount of time, and X and Y fit within the latency requirements that you open the input device with.

I am not intimately familiar with the process of sending UDP packets, but it sounds like the type of thing that is dangerous to put in the read_callback and could cause buffer overflows. Unless you can learn about the syscall(s) involved in sending UDP packets and guarantee that it will take a constant amount of time regardless of the state of the system, I'd separate that out of the read_callback.

And then once you pull the UDP packet sending code out of the real-time path, you might as well pull the encoding code out of the real time path too.

There are some mechanisms for waking up other threads which are safe to use from within write_callback and read_callback. Here's a project that compares the various latencies of some of these mechanisms: [thread-sync-latency-tests](https://github.com/wrl/thread-sync-latency-tests). So, you could try using the ring buffer approach combined with one of these tools for waking the non-realtime thread.

In general, the problem is that most syscalls and operations are optimized for *throughput*, but for real-time safe code, it doesn't matter what the throughput is; if you have a spike in latency of a single component in the real-time path, you could cause a glitch. Real-time safe code has a fixed time budget and can't afford to go above the time budget ever, even if the throughput suffers. And the lower the latency you want to achieve, the more important real-time safe code becomes.
